package Lession1;

class VariablesTheme {
    public static void main(String[] args) {
        System.out.println("1. Создание переменных и вывод их значений на консоль");
        byte numCore = 2;
        short ram  = 8;
        int ssd = 520;
        long freqCpu = 2400;
        float weight = 2.7f;
        double diag = 15.6;
        System.out.println("Количество ядер процессора: " + numCore + "\nЧастота процессора, Ггц: " + freqCpu
                + "\nОбъём ОЗУ, Гб: " + ram + "\nОбъём SSD, Гб: " + ssd + "\nВес, кг: " + weight
                + "\nДиагональ экрана: " + diag);
        System.out.println("\n2. Расчет стоимости товара со скидкой");
        int pricePen = 100;
        int priceBook = 200;
        int sum = pricePen + priceBook;
        double discount = sum * 0.11;
        double res = sum - discount;
        System.out.println("I. Сумма скидки: " + discount);
        System.out.println("II. Общая стоимость товара со скидкой: " + res);
        System.out.println("\n3. Вывод на консоль слова JAVA");
        System.out.println("    J     A    V     V    A");
        System.out.println("    J    A A    V   V    A A");
        System.out.println("J   J   AAAAA    V V    AAAAA");
        System.out.println(" J J   A     A    V    A     A");
        System.out.println("\n4. Отображение min и max значений числовых типов данных");
        byte maxByte = 127;
        System.out.println("Максимальное значение byte: " + maxByte);
        byte incByte = ++maxByte;
        System.out.println("Значение byte после инкремента: " + incByte);
        byte decByte = --incByte;
        System.out.println("Значение byte после декремента: " + decByte);
        short maxShort  = 32767;
        System.out.println("Максимальное значение short: " + maxShort);
        short incShort = ++maxShort;
        System.out.println("Значение short после инкремента: " + incShort);
        short decShort = --incShort;
        System.out.println("Значение short после декремента: " + decShort);
        int maxInt = 2147483647;
        System.out.println("Максимальное значение int: " + maxInt);
        int incInt = ++maxInt;
        System.out.println("Значение int после инкремента: " + incInt);
        int decInt = --incInt;
        System.out.println("Значение int после декремента: " + decInt);
        long maxLong  = 9223372036854775807L;
        System.out.println("Максимальное значение long: " + maxLong);
        long incLong = ++maxLong;
        System.out.println("Значение long после инкремента: " + incLong);
        long decLong = --incLong;
        System.out.println("Значение long после декремента: " + decLong);
        System.out.println("\n5. Перестановка значений переменных");
        int num1 = 2;
        int num2 = 5;
        int num3;
        System.out.println("i. с помощью третьей переменной");
        System.out.println("исходные значения переменных num1 = " + num1 + " ,num2 = " + num2);
        num3 = num1;
        num1 = num2;
        num2 = num3;
        System.out.println("новые значения переменных num1 = " + num1 + ", num2 = " + num2);
        System.out.println("ii. с помощью арифметических операций");
        System.out.println("исходные значения переменных num1 = " + num1 + ", num2 = " + num2);
        num1 += num2;
        num2 = num1 - num2;
        num1 -= num2;
        System.out.println("новые значения переменных num1 = " + num1 + ", num2 = " + num2);
        System.out.println("iii. с помощью побитовой операции");
        System.out.println("исходные значения переменных num1 = " + num1 + ", num2 = " + num2);
        num1 = num1 ^ num2;
        num2 = num2 ^ num1;
        num1 = num1 ^ num2;
        System.out.println("новые значения переменных num1 = " + num1 + ", num2 = " + num2);
        System.out.println("\n6. Вывод символов и их кодов");
        System.out.println("35 " + (char)35);
        System.out.println("38 " + (char)38);
        System.out.println("64 " + (char)64);
        System.out.println("94 " + (char)94);
        System.out.println("95 " + (char)95);
        System.out.println("\n7. Отображение количества сотен, десятков и единиц числа");
        int Num = 123;
        int X = Num / 100;
        int Y = Num % 100 / 10;
        int Z = Num % 10;
        System.out.println("Число " + Num + " содержит сотен "+ X);
        System.out.println("Число " + Num + " содержит десятков "+ Y);
        System.out.println("Число " + Num + " содержит единиц "+ Z);
        System.out.println("\n8. Вывод на консоль ASCII-арт Дюка");
        char ch1 = '/';
        char ch2 = '\\';
        char ch3 = '_';
        char ch4 = '(';
        char ch5 = ')';
        System.out.println("    " + ch1 + ch2);
        System.out.println("   " + ch1 + "  " + ch2);
        System.out.println("  " + ch1 + ch3 + ch4 + " " + ch5 + ch2);
        System.out.println(" " + ch1 + "      " + ch2);
        System.out.println("" + ch1 + ch3 + ch3 + ch3 + ch3 + ch1 + ch2 + ch3 + ch3 + ch2);
        System.out.println("\n9. Произведение и сумма цифр числа");
        int N = 345;
        int Num1 = N / 100;
        int Num2 = N % 100 / 10;
        int Num3 = N % 10;
        int summ = Num1 + Num2 + Num3;
        int mult = Num1 * Num2 * Num3;
        System.out.println("Сумма цифр числа " + N + " = " + summ);
        System.out.println("Произведение цифр числа " + N + " = " + mult);
        System.out.println("\n10. Преобразование секунд");
        int taim = 86399;
        int hour = taim / 3600;
        int min = taim % 3600 / 60;
        int sec = taim % 60;
        System.out.println("в " + taim + " секундах: " + hour  + ":" + min + ":" + sec);
    }
}
